[package]
edition = "2021"
name = "gfb"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
serde = {version = "1.0.156", features = ["derive"]}
serde_json = "1.0.94"
