[package]
edition = "2021"
name = "gfb"
version = "0.2.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.14"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
