name: Release Build
on:
  workflow_dispatch:
  push:
    tags:
      - "release/v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --verbose

  build_macos:
    name: Building for MacOS
    runs-on: macos-12
    needs: test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build and Package
        id: build-n-package
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_DEVELOPER_ID_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_DEVELOPER_ID_CERTIFICATE_PWD }}
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
        run: bash ./scripts/build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.build-n-package.outputs.DIST_FILENAME }}
          path: ${{ steps.build-n-package.outputs.DIST_PATH }}
