name: Perform a Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish Distributions
    runs-on: macos-12
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # Push binary to crates.io
          cargo login && cargo publish
