name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  build:
    name: "Build git-branch-favorite on ${{matrix.os}}"
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
      - uses: actions/checkout@v2
      - name: Build Dist
        run: cargo build --release --verbose
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
            name: "gfb-${{matrix.os}}"
            path: target/release/(gfb).*
            if-no-files-found: warn
    
